### ISSUE TITLE
elliott and isaw content need minor tweaks

### ISSUE THREAD

**Issue by paregorios** [FitzwilliamMuseum/ahrc-linking-islands#1]

**Comment by paregorios** [comment]
I'll work on this in [branch issue1](https://github.com/FitzwilliamMuseum/ahrc-linking-islands/tree/issue1) and issue a pull request when ready.

**Comment by portableant** [comment]
Good egg!

**Comment by portableant** [comment]
Super, thank you and it is great to get going on this. Jekyll is super for small things like this. Zero cost and great security.
D

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by portableant** [comment]
Closed in 74268f0f976857414d9ea47871cca2c0a9b0731b
